<?php
//App::import('Vendor', 'aws', array('file' => 'aws/aws-autoloader.php'));
//use Aws\S3\S3Client;
App::uses('StorageAmazon', 'Storage.Lib');
class StoragesController extends StorageAppController
{
    public $photoSizes = false;
    public $s3 = false;
    public $s3Config = array();

    public function beforeFilter()
    {
        parent::beforeFilter(); // TODO: Change the autogenerated stub
        $this->loadModel('Photo.Photo');
        $this->loadModel('Storage.StorageAwsObjectMap');

    }

    public function admin_index()
    {
    }
    public function index()
    {
    }
}